# 创建公众号表
CREATE TABLE IF NOT EXISTS WXPUBLIC(
  `WXPUBLIC_CODE` INT NOT NULL AUTO_INCREMENT,
  `WXPUBLIC_OPENID` VARCHAR(45) NOT NULL,
  `WXPUBLIC_NAME` VARCHAR(45) NOT NULL,
  `WXPUBLIC_NICKNAME` VARCHAR(45) NOT NULL,
  `WXPUBLIC_HEADIMG` BLOB NOT NULL,
  `WXPUBLIC_QRCODE` BLOB NOT NULL,
  `WXPUBLIC_APPID` VARCHAR(45) NOT NULL,
  `WXPUBLIC_APPSERCT` VARCHAR(45) NOT NULL,
  `WXPUBLIC_TOKEN` VARCHAR(45) NOT NULL,
  `WXPUBLIC_AESKEY` VARCHAR(45) NOT NULL,
  `WXPUBLIC_URL` VARCHAR(45) NOT NULL,
  `WXPUBLIC_HEADIMG_NAME` VARCHAR(45) NOT NULL,
  `WXPUBLIC_QRCODE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`WXPUBLIC_CODE`))
  ENGINE = InnoDB