-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 11:20:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mdweixin
-- -----------------------------------------------------
-- 微信公众号

-- -----------------------------------------------------
-- Schema mdweixin
--
-- 微信公众号
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mdweixin` DEFAULT CHARACTER SET utf8 ;
USE `mdweixin` ;

-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_PUBLIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_PUBLIC` (
  `PUBLIC_CODE` VARCHAR(255) NOT NULL COMMENT '公众号 code',
  `OPEN_ID` VARCHAR(255) NOT NULL COMMENT '公众号 openid',
  `PUBLIC_NAME` VARCHAR(255) NOT NULL COMMENT '公众号名称',
  `PUBLIC_NICKNAME` VARCHAR(255) NOT NULL COMMENT '公众微信号',
  `APP_ID` VARCHAR(255) NOT NULL COMMENT '应用 ID',
  `APP_SERCT` VARCHAR(255) NOT NULL COMMENT '应用秘钥',
  `TOKEN` VARCHAR(255) NOT NULL COMMENT '令牌',
  `AESKEY` VARCHAR(255) NOT NULL COMMENT '消息加密密钥',
  `URL` VARCHAR(255) NOT NULL COMMENT '服务器地址',
  `CREATOR` VARCHAR(255) NULL COMMENT '创建者',
  `CREATE_DATE` VARCHAR(50) NULL COMMENT '创建时间',
  `MODIFY_DATE` VARCHAR(50) NULL COMMENT '修改时间',
  `MODIFYER` VARCHAR(255) NULL COMMENT '修改人',
  `DEL_FLAG` INT(11) NULL DEFAULT 0 COMMENT '是否删除。0为没删除，1为已删除',
  `SYSTEM_CODE` VARCHAR(255) NULL COMMENT '系统标识\n',
  `IMG_CODE` VARCHAR(255) NULL,
  PRIMARY KEY (`PUBLIC_CODE`),
  UNIQUE INDEX `OPEN_ID_UNIQUE` (`OPEN_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '公众号管理模块';


-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_PUB_CONFIG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_PUB_CONFIG` (
  `CONFIG_CODE` VARCHAR(255) NOT NULL COMMENT '主键',
  `PUBLIC_CODE` VARCHAR(255) NOT NULL COMMENT '公众号主键',
  `MENU_USE_FLAG` INT(11) NULL DEFAULT 0 COMMENT '是否开启自定义菜单。0为关闭，1为开启。默认为0',
  `KEFU_USE_FLAG` INT(11) NULL DEFAULT 0 COMMENT '消息管理中是否开启客服服务。0为关闭，1为开启。默认为0',
  `PUSH_USE_FLAG` INT(11) NULL DEFAULT 0 COMMENT '是否开启定点推送。0为关闭，1为打开。默认为0',
  `KEFU_OFFLINE_MESSAGE` VARCHAR(255) NULL DEFAULT '客服为您服务' COMMENT '客服不在线的时候的提示内容',
  `KEFU_ONLINE_MESSAGE` VARCHAR(255) NULL DEFAULT '服务结束' COMMENT '客服在线等时候的提示内容',
  PRIMARY KEY (`CONFIG_CODE`),
  UNIQUE INDEX `PUBLIC_CODE_UNIQUE` (`PUBLIC_CODE` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '公众号的配置-关注时回复、非关键词消息默认回复、关键词回复、自定义菜单、开启消息转发至客服、客服功能、定点推送';


-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_REP_RULE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_REP_RULE` (
  `RULE_CODE` VARCHAR(255) NOT NULL COMMENT '主键',
  `PUBLIC_CODE` VARCHAR(255) NOT NULL COMMENT '公众号主键\n',
  `RULE_NAME` VARCHAR(255) NOT NULL COMMENT '规则名称',
  `USE_FLAG` INT(11) NOT NULL COMMENT '关键词回复中规则是否开启。0为关闭，1为开启。',
  `KEFU_REPLY_FLAG` INT(11) NOT NULL COMMENT '客服回复',
  `CONTENT` VARCHAR(255) NOT NULL COMMENT '回复内容',
  `CREATOR` VARCHAR(255) NULL COMMENT '创建人',
  `CREATE_DATE` VARCHAR(50) NULL COMMENT '创建时间',
  `MODIFY_DATE` VARCHAR(50) NULL COMMENT '修改时间',
  `MODIFYER` VARCHAR(255) NULL COMMENT '修改人',
  `DEL_FLAG` INT(11) NULL DEFAULT 0 COMMENT '是否删除。0为没删除，1为已删除',
  PRIMARY KEY (`RULE_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '自动回复模块--规则表';


-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_REP_KEYWORD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_REP_KEYWORD` (
  `KEYWORD_CODE` VARCHAR(255) NOT NULL COMMENT '规则主键',
  `RULE_CODE` VARCHAR(255) NOT NULL COMMENT '主键',
  `KEYWORD` VARCHAR(255) NOT NULL COMMENT '关键字',
  `MATCH_FLAG` INT(11) NOT NULL COMMENT '匹配规则，1为完全匹配，0为模糊匹配',
  `DEL_FLAG` INT(11) NULL COMMENT '是否删除。0为已删除，1为没删除。',
  PRIMARY KEY (`KEYWORD_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '自动回复模块--微信关键字表';


-- -----------------------------------------------------
-- Table `mdweixin`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`user` (
  `username` (16) NOT NULL,
  `email` (255) NOT NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_MSG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_MSG` (
  `MSG_CODE` VARCHAR(255) NOT NULL COMMENT '主键',
  `PUBLIC_CODE` VARCHAR(255) NOT NULL COMMENT '公众号主键（统一）',
  `USER_CODE` VARCHAR(255) NOT NULL COMMENT '消息来源（统一）',
  `MSG_ID` VARCHAR(255) NOT NULL COMMENT '消息id，64位整型（统一）',
  `CREATE_DATE` VARCHAR(50) NOT NULL COMMENT '消息创建时间（统一）',
  `MSG_TYPE` VARCHAR(50) NOT NULL COMMENT '消息类型',
  `CONTENT` VARCHAR(255) NULL COMMENT '文本消息时为【内容】、链接消息是为【消息标题】、地理位置消息时为【地理位置信息】',
  `MEDIA_ID` VARCHAR(255) NULL COMMENT '图片消息、语音消息、视频消息、可以调用多媒体文件下载接口拉取数据。\n',
  `URL` VARCHAR(255) NULL COMMENT '图片消息时为【图片链接】、链接消息时为【消息链接】',
  `FORMAT` VARCHAR(255) NULL COMMENT '语音格式，如amr，等',
  `RECOGNITION` VARCHAR(255) NULL COMMENT '开通语音识别后，用户每次发送语音给公众号时，微信会在推送的语音消息XML数据包中，增加一个Recongnition字段，UTF8编码',
  `THUMB_MEDIA_ID` VARCHAR(255) NULL COMMENT '视频、小视频消息缩略图的媒体id，可以调用多媒体文件下载接口拉取数据。',
  `LOCATION_X` DOUBLE NULL COMMENT '地理位置消息中的【地理位置维度】',
  `LOCATION_Y` DOUBLE NULL COMMENT '地理位置消息中的【地理位置经度】',
  `LOCATION_SCALE` DOUBLE NULL COMMENT '地理位置消息中的【地图缩放大小】',
  `DESCRIPTION` VARCHAR(255) NULL COMMENT '链接消息中的【消息描述】',
  `DEL_FLAG` INT(11) NULL DEFAULT 0 COMMENT '是否删除。0为没删除，1为已删除、',
  PRIMARY KEY (`MSG_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '消息管理模块--用户发送的消息，消息类型有文本、图片、语音、视频、小视频、地理位置、链接、图文。';


-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_MSG_PUSH_RECORD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_MSG_PUSH_RECORD` (
  `RECORD_CODE` VARCHAR(255) NOT NULL COMMENT '定点消息记录主键',
  `PUSH_CODE` VARCHAR(255) NOT NULL COMMENT '定点推送主键',
  `USER_CODE` VARCHAR(255) NOT NULL COMMENT '推送的用户openid\n',
  `PUSH_DATE` VARCHAR(255) NOT NULL COMMENT '推送的时间',
  `PUSH_STATE` INT(11) NULL COMMENT '推送的状态：（暂时没有）',
  `DEL_FLAG` INT(11) NULL DEFAULT 0 COMMENT '是否删除，0表示存在，1表示删除',
  PRIMARY KEY (`RECORD_CODE`),
  UNIQUE INDEX `PUSH_CODE_UNIQUE` (`PUSH_CODE` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '消息管理模块--定点推送的记录，记录推送日期、推送人数。\n\n';


-- -----------------------------------------------------
-- Table `mdweixin`.`MDWXMSG_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MDWXMSG_copy1` (
  `WXMSG_CODE` INT NOT NULL COMMENT '消息 code',
  `WXFROMUSER` VARCHAR(45) NOT NULL COMMENT '消息来源',
  `WXTOUSER` VARCHAR(45) NOT NULL COMMENT '消息接受者',
  `WXCREATE_TIME` TINYINT(1) NOT NULL COMMENT '消息创建时间',
  `WXTYPE` TINYINT(1) NOT NULL COMMENT '消息类型',
  `WXMEDIAID` VARCHAR(45) NULL COMMENT '语音消息媒体id，可以调用多媒体文件下载接口拉取数据。',
  `WXFORMAT` VARCHAR(45) NULL COMMENT '语音格式：amr',
  `WXMSGID` MEDIUMTEXT NULL COMMENT '消息id，64位整型',
  `WXRECOGNITION` VARCHAR(45) NULL COMMENT '语音识别结果，UTF8编码',
  PRIMARY KEY (`WXMSG_CODE`))
ENGINE = InnoDB
COMMENT = '消息管理模块--用户发送的消息，可能是文本、图片、语音。';


-- -----------------------------------------------------
-- Table `mdweixin`.`MDWXMSG_copy2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MDWXMSG_copy2` (
  `WXMSG_CODE` INT NOT NULL COMMENT '消息 code',
  `WXFROMUSER` VARCHAR(45) NOT NULL COMMENT '消息来源',
  `WXTOUSER` VARCHAR(45) NOT NULL COMMENT '消息接受者',
  `WXCREATE_TIME` TINYINT(1) NOT NULL COMMENT '消息创建时间',
  `WXTYPE` TINYINT(1) NOT NULL COMMENT '消息类型',
  `WXMEDIAID` VARCHAR(45) NULL COMMENT '语音消息媒体id，可以调用多媒体文件下载接口拉取数据。',
  `WXFORMAT` VARCHAR(45) NULL COMMENT '语音格式：amr',
  `WXMSGID` MEDIUMTEXT NULL COMMENT '消息id，64位整型',
  `WXRECOGNITION` VARCHAR(45) NULL COMMENT '语音识别结果，UTF8编码',
  PRIMARY KEY (`WXMSG_CODE`))
ENGINE = InnoDB
COMMENT = '消息管理模块--用户发送的消息，可能是文本、图片、语音。';


-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_PUB_IMG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_PUB_IMG` (
  `IMG_CODE` VARCHAR(255) NOT NULL COMMENT '主键',
  `HEADIMG` BLOB NOT NULL COMMENT '微信公众号的头像文件',
  `QRCODE` BLOB NOT NULL COMMENT '微信公众号的二维码图片文件',
  PRIMARY KEY (`IMG_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '公众号管理--头像、二维码';


-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_REPLY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_REPLY` (
  `REPLY_CODE` VARCHAR(255) NOT NULL COMMENT '主键',
  `PUBLIC_CODE` VARCHAR(255) NOT NULL COMMENT '公众号主键',
  `REPLY_TYPE` INT(11) NOT NULL COMMENT '消息回复类型。0为关注时回复，1为非关键词消息默认回复，2为关键词回复。',
  `CONTENT` VARCHAR(255) NULL COMMENT '回复的内容',
  `REPLY_FLAG` INT(11) NOT NULL DEFAULT 1 COMMENT '回复是否开启。0为关闭，1为开启，默认为1开启',
  PRIMARY KEY (`REPLY_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '自动回复模块，有关注时回复、非关键词回复、关键词回复三个主要功能。';


-- -----------------------------------------------------
-- Table `mdweixin`.`MP_YY_MSG_PUSH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`MP_YY_MSG_PUSH` (
  `PUSH_CODE` VARCHAR(255) NOT NULL COMMENT '推送消息 code',
  `PUBLIC_CODE` VARCHAR(255) NOT NULL COMMENT '公众号主键code',
  `PUSH_NAME` VARCHAR(255) NOT NULL COMMENT '推送名称',
  `LATITUDE` DOUBLE NOT NULL COMMENT '纬度',
  `LONGITUDE` DOUBLE NOT NULL COMMENT '经度',
  `RADIUS` DOUBLE NOT NULL COMMENT '推送半径',
  `CONTENT` VARCHAR(255) NOT NULL COMMENT '推送内容',
  `PUSH_FLAG` INT(11) NOT NULL COMMENT '是否开启该推送。0为关闭，1位开启。（推送记录）',
  `CREATOR` VARCHAR(255) NULL COMMENT '创建者',
  `CREATE_DATE` VARCHAR(50) NULL COMMENT '创建时间',
  `MODIFY_DATE` VARCHAR(50) NULL COMMENT '修改时间',
  `MODIFYER` VARCHAR(255) NULL COMMENT '修改者',
  `DEL_FLAG` INT(11) NULL DEFAULT 0 COMMENT '是否删除。0为没删除，1为已删除',
  `PUSH_STATE` VARCHAR(255) NULL COMMENT '消息状态',
  PRIMARY KEY (`PUSH_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '消息管理模块--定点推送消息记录表（只会推一次）';

USE `mdweixin` ;

-- -----------------------------------------------------
-- Placeholder table for view `mdweixin`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdweixin`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mdweixin`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdweixin`.`view1`;
USE `mdweixin`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
